spring:
  application:
    name: Thread Async
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  name: Thread Async
  version: 1.0
